services:
  database: 
    image: mongo:latest
    container_name: home-inventory-db-dev
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  backend:
    build:
      context: ./home-inventory-backend
      dockerfile: Dockerfile.dev
    container_name: home-inventory-backend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./home-inventory-backend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  frontend:
    build:
      context: ./home-inventory-frontend
      dockerfile: Dockerfile.dev
    container_name: home-inventory-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./home-inventory-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    